import turtle
from turtle import*
screen = turtle.Screen()
t= turtle.Turtle()
speed(6)
def orange():
    t.penup()
    t.goto(-200,125)
    t.pendown()
    t.color('orange')
    t.begin_fill()
    t.forward(400)
    t.right(90)
    t.forward(84)
    t.right(90)
    t.forward(400)
    t.end_fill()
    t.left(90)
    t.forward(84)
def green():
    t.color('green')
    t.begin_fill()
    t.forward(84)
    t.left(90)
    t.forward(400)
    t.left(90)
    t.forward(84)
    t.left(90)
    t.forward(400)
    t.end_fill()
def stick():
    t.color('brown')
    t.pensize(10)
    t.penup()
    t.goto(-200,125)
    t.right(270)
    t.pendown()
    t.forward(800) 
def ashokachakra():
    t.penup()
    t.goto(-30,0)
    t.pendown()
    t.color('navy')
    t.begin_fill()
    t.circle(35)
    t.end_fill()
def whitecircle():
    t.penup()
    t.goto(-25,0)
    t.pendown()
    t.color('white')
    t.begin_fill()
    t.circle(30)
    t.end_fill()
def smallbluecircle():
     t.color('navy')
     t.penup()
     t.goto(-5,0)
     t.pendown()
     t.begin_fill()
     t.circle(10)
     t.end_fill()
def spokes():
     t.penup()
     t.goto(-1,0)
     t.pendown()
     t.pensize(1)
     for i in range(24):
         t.forward(35)
         t.backward(35)
         t.left(15)

orange()
green()
stick()
ashokachakra()
whitecircle()
smallbluecircle()
spokes()
turtle.done()
